image: node:16

stages:
  - test

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

cache:
  paths:
    - /root/.cache/
    - $CI_PROJECT_DIR/node_modules/
  key: ${CI_COMMIT_REF_SLUG}

test:
  stage: test
  image: mcr.microsoft.com/playwright:focal
  script:
    - cd -- "$CI_PROJECT_DIR"
    - npm ci
    - npm run test:unit
    - npm run prod &
    - sleep 15 && curl http://localhost:3000
    - npx playwright install
    - npm run test:e2e
  timeout: 15m
